name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Auth to ACR
      run: echo ${{ secrets.ACR_PASSWORD }} | docker login --username test123j --password-stdin test123j.azurecr.io
    - name: Build the Docker image
      run: 
        docker build . --file Dockerfile --tag test123j.azurecr.io/actions/codecoveragesummary:${{ github.run_number }}

    - name: Push the Docker iamge
      run: | 
        docker push test123j.azurecr.io/actions/codecoveragesummary:${{ github.run_number }}
        # docker push test123j.azurecr.io/actions/codecoveragesummary:latest
